apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-synthesis-worker
  labels:
    app: {{ .Release.Name }}-synthesis-worker
spec:
  replicas: {{ .Values.synthesis.workerCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-synthesis-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-synthesis-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.synthesis.image.repository }}:{{ .Values.synthesis.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ if .Values.redis.host }}{{ .Values.redis.host }}{{ else }}{{ .Release.Name }}-redis{{ end }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: WORKER_TYPE
              value: "synthesis"
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 1000m
              memory: 2Gi
