"""RISC-V Custom ML ISA Generation — generate custom instructions for neural network ops."""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any
import json


@dataclass
class RiscVCustomOp:
    mnemonic: str
    opcode_space: int
    funct3: int
    funct7: int
    latency_cycles: int = 1
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "mnemonic": self.mnemonic,
            "opcode_space": self.opcode_space,
            "funct3": self.funct3,
            "funct7": self.funct7,
            "latency_cycles": self.latency_cycles,
            "description": self.description,
        }

    def to_chisel(self) -> str:
        return f"""\
// Custom RISC-V instruction: {self.mnemonic}
// Opcode space: 0x{self.opcode_space:02x}, funct3: {self.funct3}, funct7: {self.funct7}
// Latency: {self.latency_cycles} cycles
class {self.mnemonic.upper()} extends CustomInstruction {{
  def decode: Unit = {{
    when (io.instruction(6, 0) === 0x{self.opcode_space:02x}.U) {{
      io.out.valid := true.B
      io.out.pc := io.pc
      io.out.inst := io.instruction
    }}
  }}

  def execute: Unit = {{
    io.out.done := RegNext(io.out.valid, false.B, {self.latency_cycles})
  }}
}}
"""

    def to_gas_asm(self) -> str:
        return f"""\
// GAS assembler extension for {self.mnemonic}
.macro {self.mnemonic.upper()} rs1, rs2, rd
    .insn r 0x{self.opcode_space:02x}, {self.funct3}, {self.funct7}, \\rd, \\rs1, \\rs2
.endm
"""


class RiscVExtensionGenerator:
    """Generate custom RISC-V ISA extensions from TPT-IR op profiles."""

    OP_CUSTOM_MAP = {
        "matmul": RiscVCustomOp("vmmul", 0x0B, 0, 1, 4, "Vector matrix multiply"),
        "fused_matmul_relu": RiscVCustomOp("vmmulrelu", 0x0B, 1, 1, 5, "Fused matmul + ReLU"),
        "fused_matmul_gelu": RiscVCustomOp("vmmulgelu", 0x0B, 2, 1, 6, "Fused matmul + GELU"),
        "fused_add_relu": RiscVCustomOp("vaddrelu", 0x0B, 3, 1, 3, "Fused add + ReLU"),
        "softmax": RiscVCustomOp("vsoftmax", 0x0B, 4, 1, 8, "Vector softmax"),
        "layernorm": RiscVCustomOp("vlayernorm", 0x0B, 5, 1, 6, "Vector layer normalization"),
        "attention": RiscVCustomOp("vattention", 0x0B, 6, 1, 10, "Multi-head attention"),
    }

    def analyze(self, op_counts: dict[str, int]) -> list[tuple[str, int]]:
        ranked = sorted(op_counts.items(), key=lambda x: -x[1])
        return [(op, count) for op, count in ranked if op in self.OP_CUSTOM_MAP]

    def generate_extensions(self, top_ops: list[str], top_n: int = 8) -> list[RiscVCustomOp]:
        ops = []
        for op in top_ops[:top_n]:
            if op in self.OP_CUSTOM_MAP:
                ops.append(self.OP_CUSTOM_MAP[op])
        return ops

    def generate_chisel(self, ops: list[RiscVCustomOp]) -> str:
        parts = [
            "// Auto-generated RISC-V Custom ML ISA Extension",
            "// Generated by TPT Alloy RISC-V ISA Generator",
            "",
            "package tpt.alloy.isa",
            "",
            "import chisel3._",
            "import chisel3.util._",
            "",
        ]
        for op in ops:
            parts.append(op.to_chisel())
        return "\n".join(parts)

    def generate_gas_patch(self, ops: list[RiscVCustomOp]) -> str:
        parts = [
            "# Auto-generated GAS assembler extension for TPT Custom ML ISA",
            "# Generated by TPT Alloy RISC-V ISA Generator",
            "",
        ]
        for op in ops:
            parts.append(op.to_gas_asm())
        return "\n".join(parts)

    def estimate_speedup(self, ops: list[RiscVCustomOp], op_counts: dict[str, int]) -> float:
        total_custom_cycles = 0
        total_baseline_cycles = 0
        for op in ops:
            count = op_counts.get(op.mnemonic.lower().replace("vmmul", "matmul").replace("vadd", "add"), 0)
            total_custom_cycles += count * op.latency_cycles
            total_baseline_cycles += count * 10
        if total_baseline_cycles == 0:
            return 1.0
        return total_baseline_cycles / max(total_custom_cycles, 1)
